# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 85e37516ba446898aaaa2b219aa80736f014064c0d1717f94d4b5f22452f6116d5ce8c94655fb54d6aa67678cee0b41276149049bd44f684fb13a28df51d686e

test:
  secret_key_base: b9db511956a501ec96d360cea5b65d857a6063fd7bd2bdd7fdd9b2bca1ec59454a7fdf18e51caf14649485738b1f88e2e6ec1062d09dcb0a2fbed8da18a389c6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
